# Generated by Django 3.1.2 on 2020-11-11 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_auto_20201106_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/welcome', verbose_name='欢迎图片')),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='father_text',
            field=models.TextField(blank=True, default='', verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 12, 41, 16, 587868), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 12, 41, 16, 587868), verbose_name='创建时间'),
        ),
    ]
