# Generated by Django 3.1.2 on 2020-11-17 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0004_auto_20201112_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='', max_length=5, verbose_name='分数')),
                ('sum', models.IntegerField(default=0, verbose_name='计数')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 16, 58, 15, 690107), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 16, 58, 15, 690107), verbose_name='创建时间'),
        ),
    ]
