# Generated by Django 3.1.2 on 2020-11-17 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0005_auto_20201117_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='位置')),
                ('sum', models.IntegerField(default=0, verbose_name='访问量')),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='guide',
            field=models.ImageField(blank=True, null=True, upload_to='image/point', verbose_name='导览图片'),
        ),
        migrations.AddField(
            model_name='point',
            name='order',
            field=models.IntegerField(default=0, verbose_name='导览顺序'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 17, 34, 30, 650696), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 17, 34, 30, 651693), verbose_name='创建时间'),
        ),
    ]
