# Generated by Django 3.1.2 on 2020-11-18 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0006_auto_20201117_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 17, 54, 30, 252604), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 17, 54, 30, 253602), verbose_name='创建时间'),
        ),
    ]
