# Generated by Django 3.1.2 on 2020-11-18 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0007_auto_20201118_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 18, 11, 58, 105495), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 18, 11, 58, 106472), verbose_name='创建时间'),
        ),
    ]
