# Generated by Django 3.1.2 on 2020-11-19 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0009_auto_20201118_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='guide',
        ),
        migrations.AddField(
            model_name='floor',
            name='panorama',
            field=models.ImageField(blank=True, null=True, upload_to='image/floor', verbose_name='全景图片'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 15, 17, 28, 583275), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 15, 17, 28, 583275), verbose_name='创建时间'),
        ),
    ]
